#include<iostream>
using namespace std;
main()
{
int number1;
int number2;
int number3;
int number4;
int number5;
int number6;
int number7;
int number8;
int number9;
int number10;
int number11;
int number12;
int number13;
int number14;
int number15;
cout<<"Enter 1st number:";
cin>>number1;
cout<<"Enter 2nd number:";
cin>>number2;
cout<<"Enter 3rd number:";
cin>>number3;
cout<<"Enter 4th number:";
cin>>number4;
cout<<"Enter 5th number:";
cin>>number5;
cout<<"Enter 6th number:";
cin>>number6;
cout<<"Enter 7th number:";
cin>>number7;
cout<<"Enter 8th number:";
cin>>number8;
cout<<"Enter 9th number:";
cin>>number9;
cout<<"Enter 10th number:";
cin>>number10;
cout<<"Enter 11th number:";
cin>>number11;
cout<<"Enter 12th number:";
cin>>number12;
cout<<"Enter 13th number:";
cin>>number13;
cout<<"Enter 14th number:";
cin>>number14;
cout<<"Enter 15th number:";
cin>>number15;
float result1;
float result2;
float result3;
result1= number1+number2+number3+number4+number5;
result2= number6*number7*number8*number9*number10;
result3=number11-number12-number13-number14-number15;
float total;
total= (result1+result2)-result3;
cout<<"Total:"<<total;
}
